"""add occurrence_count to security_events

Revision ID: 7e50057572e6
Revises: 0190fee89773
Create Date: 2026-09-02 02:31:55.371132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e50057572e6'
down_revision: Union[str, None] = '0190fee89773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_events', sa.Column('occurrence_count', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_events', 'occurrence_count')
    # ### end Alembic commands ###
